import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "rock-paper-scissors-game",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4">
        <header className="text-xl font-bold leading-[4rem]">rock-paper-scissors-game</header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">
          © {new Date().getFullYear()} rock-paper-scissors-game
        </footer>
      </body>
    </html>
  );
}
